apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: aquo10o4s-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:18a6e62b082caff5072d71ebd7e711f4c90fd3ad@sha256:d074da4e288a6e3cdcc24ae5793ae2c5af733390a11525255fbc1bc6f6ed8472
          name: container-image
